### ISSUE TITLE
Szia!

### ISSUE THREAD

**Issue by SzotsGabor** [SzilBalazs/BlackCore#34]
Végre újra egy magyar sakkprogram!

Magam még 2004-ben rendeztem bajnokságot magyar sakkprogramoknak. Aztán valahogy elfogytak, ezért különös öröm most újra látni egyet.

A most kiadott verzióhoz annyit fűznék, hogy nem 1.0-nak, hanem V0-nak hívja magát; ez kissé zavaró.

U.i.: SzilBalazs-ból nem derül ki teljes neved; elárulnád? És azt is, hogy hová valósi vagy.

Szőts Gábor
(a CCRL tesztcsoport tagja)

**Comment by SzilBalazs** [comment]
Kedves Gábor!

A teljes nevem Szilágyi Balázs én 15 éves Budapesti gimnazista vagyok. A verzió számot 1.1-ben egyéb apróságokkal együtt javítani fogom, köszönöm a visszajelzést. Bármilyen egyéb javaslatot szívesen fogadok BlackCore-ral kapcsolatban.

Szilágyi Balázs

**Comment by SzotsGabor** [comment]
Kösz a választ. Következő versenyemen elindítom BlackCore-t. Remélem, a következő CCRL-frissítést eléri.

**Comment by SzotsGabor** [comment]
Íme az első eredmény: http://www.computerchess.org.uk/ccrl/404/cgi/engine_details.cgi?match_length=30&each_game=1&print=Details&each_game=1&eng=BlackCore%201.0%2064-bit#BlackCore_1_0_64-bit

**Comment by SzilBalazs** [comment]
Köszönöm szépen az infókat, remélem, hogy az elkövetkező napokban bejelenhetem az 1.1 verziót ami remélhetőleg jóval erősebb lesz a v1.0-nál. Ezt itt, vagy a CCRL fórumokon tegyem meg?

Válaszát előre is köszönöm: Balázs

**Comment by SzotsGabor** [comment]
Ne itt. Legjobb a CCRL Public fóruma vagy TalkChess General Topics fóruma: http://talkchess.com/forum3/viewforum.php?f=2
Ott akár új bejegyzést is nyithatsz vagy megkeresheted a New engine releases... szálon futó bejelentéseket, http://talkchess.com/forum3/viewtopic.php?f=2&t=80208 és ott közzé teheted a magadét.

Üdv: Gábor
