### ISSUE TITLE
error: 'aligned_alloc on gcc

### ISSUE THREAD

**Issue by Negatil07** [SzilBalazs/BlackCore#43]
tt.cpp:` In function 'void ttResize(unsigned int)':
tt.cpp:51:40: error: 'aligned_alloc' was not declared in this scope
   51 |     tt.table = static_cast<TTBucket *>(aligned_alloc((1ULL << 20), tt.bucketCount * sizeof(TTBucket)));
      |                                        ^~~~~~~~~~~~~
make: *** [Makefile:64: objects/tt.o] Error 1

**Comment by SzilBalazs** [comment]
Hi!
Could you please update your compiler and report if the error is still persist? g++ 11 should do, but for the best performance I would suggest 12.
